version: "2.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-semantic-elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    restart: always
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: es-semantic-kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    restart: always
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

  flask:
    container_name: es-semantic-flask
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - kibana
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${FLASK_PORT}:5000
    environment:
      - ES_HOST=elasticsearch
    restart: always
    profiles:
      - backend

  flask-cuda:
    container_name: es-semantic-flask
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - kibana
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${FLASK_PORT}:5000
    environment:
      - ES_HOST=elasticsearch
    restart: always
    profiles:
      - backend-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
